Update dev.yml

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -15,16 +15,16 @@ jobs:
       - name: Print Hello World
         run: echo "Hello, World!"
 
+      - name: Intentionally Fail
+        run: exit 1
+
       - name: Slack Notification - Success
         if: success()
         run: echo "Success notification"
-
-      - name: Print Hello World
-        run: echo "Hello, World!"
 
       - name: Slack Notification - Failure
         if: failure()
         run: echo "Failure notification"
 
       - name: Print Hello World
-        run: echo "FAILED. "
+        run: echo "FAILED."
